// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXi60RFrECURkyeAAX-N1QrT98Ox6BqkI',
    appId: '1:395850115907:web:cd2c1bec96a80eb1d65df6',
    messagingSenderId: '395850115907',
    projectId: 'student-directory-5f6a1',
    authDomain: 'student-directory-5f6a1.firebaseapp.com',
    storageBucket: 'student-directory-5f6a1.firebasestorage.app',
    measurementId: 'G-BXKF7CH7FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdry7MdEQHG-3SCPQsoRh2SmIwcalB92I',
    appId: '1:395850115907:android:7744bbcdcc9544bdd65df6',
    messagingSenderId: '395850115907',
    projectId: 'student-directory-5f6a1',
    storageBucket: 'student-directory-5f6a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARuMgQKadn0rFJ5qnP-WgGKnSrf3k4bEM',
    appId: '1:395850115907:ios:2779ecfeba45d397d65df6',
    messagingSenderId: '395850115907',
    projectId: 'student-directory-5f6a1',
    storageBucket: 'student-directory-5f6a1.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARuMgQKadn0rFJ5qnP-WgGKnSrf3k4bEM',
    appId: '1:395850115907:ios:2779ecfeba45d397d65df6',
    messagingSenderId: '395850115907',
    projectId: 'student-directory-5f6a1',
    storageBucket: 'student-directory-5f6a1.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXi60RFrECURkyeAAX-N1QrT98Ox6BqkI',
    appId: '1:395850115907:web:07354f49a00bb202d65df6',
    messagingSenderId: '395850115907',
    projectId: 'student-directory-5f6a1',
    authDomain: 'student-directory-5f6a1.firebaseapp.com',
    storageBucket: 'student-directory-5f6a1.firebasestorage.app',
    measurementId: 'G-YX60Y7ZLK7',
  );
}
